name: riyales
description: A Flutter application for real-time rates of currency, gold, crypto, and stocks.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & UX
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_staggered_animations: ^1.1.1
  vibration: ^3.1.3
  dots_indicator: ^2.1.0

  # State Management
  flutter_riverpod: ^2.6.1

  # Networking
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4

  # Local Storage
  shared_preferences: ^2.5.3

  # Utilities
  intl: ^0.20.2
  equatable: ^2.0.7
  smooth_corner: ^1.1.1
  flutter_cache_manager: ^3.4.1
  palette_generator: ^0.3.3+7
  url_launcher: ^6.3.2
  video_player: ^2.10.0
  flutter_launcher_icons: ^0.14.4
  provider: ^6.1.5
  device_info_plus: ^11.5.0
  universal_platform: ^1.1.0
  web_smooth_scroll: ^2.0.0
  auto_size_text: ^3.0.0
  uuid: ^4.5.1
  package_info_plus: ^8.3.0
  universal_html: ^2.2.4
  http: ^1.4.0
  cupertino_onboarding: ^1.3.0
  protobuf: ^4.1.0
  fixnum: ^1.1.1
  seo: ^0.0.10
  url_strategy: ^0.3.0
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/config/
    - assets/icons/flags/
    - assets/icons/crypto/
    - assets/icons/commodity/
    - assets/icons/

  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn.ttf
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
    - family: CourierPrime
      fonts:
        - asset: assets/fonts/CourierPrime.ttf
    - family: Onest
      fonts:
        - asset: assets/fonts/Onest.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/riyales.png"
