import 'dart:ui';

class CurrencyMaps {
  static Map<String, String> currencyNamesEn = {
  'usd': 'US Dollar',
  'eur': 'Euro',
  'gbp': 'British Pound',
  'chf': 'Swiss Franc',
  'cad': 'Canadian Dollar',
  'aud': 'Australian Dollar',
  'sek': 'Swedish Krona',
  'nok': 'Norwegian Krone',
  'rub': 'Russian Ruble',
  'thb': 'Thai Baht',
  'sgd': 'Singapore Dollar',
  'hkd': 'Hong Kong Dollar',
  'azn': 'Azerbaijani Manat',
  'amd': 'Armenian Dram',
  'dkk': 'Danish Krone',
  'aed': 'UAE Dirham',
  'jpy': 'Japanese Yen',
  'try': 'Turkish Lira',
  'cny': 'Chinese Yuan',
  'sar': 'Saudi Riyal',
  'inr': 'Indian Rupee',
  'irr': 'IR Toman',
  'myr': 'Malaysian Ringgit',
  'afn': 'Afghan Afghani',
  'kwd': 'Kuwaiti Dinar',
  'iqd': 'Iraqi Dinar',
  'bhd': 'Bahraini Dinar',
  'omr': 'Omani Rial',
  'qar': 'Qatari Riyal',
  'emami1': 'Imami Gold Coin',
  'azadi1g': 'Azadi Gold Coin',
  'azadi1': 'Full Azadi Coin',
  'azadi1_2': 'Half Azadi Coin',
  'azadi1_4': 'Quarter Azadi Coin',
  'mithqal': 'Mesqal',
  'gol18': 'Gold 18K',
  'ounce': 'Gold Ounce',
  'bitcoin': 'Bitcoin',
  };

  static Map<String, String> currencyNamesFa = {
  'usd': 'دلار آمریکا',
  'eur': 'یورو',
  'gbp': 'پوند بریتانیا',
  'chf': 'فرانک سوئیس',
  'cad': 'دلار کانادا',
  'aud': 'دلار استرالیا',
  'sek': 'کرون سوئد',
  'nok': 'کرون نروژ',
  'rub': 'روبل روسیه',
  'thb': 'بات تایلند',
  'sgd': 'دلار سنگاپور',
  'hkd': 'دلار هنگ کنگ',
  'azn': 'منات آذربایجان',
  'amd': 'درام ارمنستان',
  'dkk': 'کرون دانمارک',
  'aed': 'درهم امارات',
  'jpy': 'ین ژاپن',
  'try': 'لیر ترکیه',
  'cny': 'یوان چین',
  'sar': 'ریال عربستان',
  'inr': 'روپیه هند',
  'irr': 'تومان ایران',
  'myr': 'رینگیت مالزی',
  'afn': 'افغانی افغانستان',
  'kwd': 'دینار کویت',
  'iqd': 'دینار عراق',
  'bhd': 'دینار بحرین',
  'omr': 'ریال عمان',
  'qar': 'ریال قطر',
  'emami1': 'سکه امامی',
  'azadi1g': 'سکه بهار آزادی گرمی',
  'azadi1': 'سکه تمام بهار آزادی',
  'azadi1_2': 'نیم سکه بهار آزادی',
  'azadi1_4': 'ربع سکه بهار آزادی',
  'mithqal': 'مثقال',
  'gol18': 'طلای ۱۸ عیار',
  'ounce': 'اونس طلا',
  'bitcoin': 'بیت‌کوین',
  };

  static Map<String, String> currencySymbols = {
  'usd': '🇺🇸',
  'eur': '🇪🇺',
  'gbp': '🇬🇧',
  'chf': '🇨🇭',
  'cad': '🇨🇦',
  'aud': '🇦🇺',
  'sek': '🇸🇪',
  'nok': '🇳🇴',
  'rub': '🇷🇺',
  'thb': '🇹🇭',
  'sgd': '🇸🇬',
  'hkd': '🇭🇰',
  'azn': '🇦🇿',
  'amd': '🇦🇲',
  'dkk': '🇩🇰',
  'aed': '🇦🇪',
  'jpy': '🇯🇵',
  'try': '🇹🇷',
  'cny': '🇨🇳',
  'sar': '🇸🇦',
  'inr': '🇮🇳',
  'irr': '🇮🇷',
  'myr': '🇲🇾',
  'afn': '🇦🇫',
  'kwd': '🇰🇼',
  'iqd': '🇮🇶',
  'bhd': '🇧🇭',
  'omr': '🇴🇲',
  'qar': '🇶🇦',
  'emami1': '🪙 ',
  'azadi1g': '🟡',
  'azadi1': '🟡',
  'azadi1_2': '🟡',
  'azadi1_4': '🟡',
  'mithqal': '⚖️',
  'gol18': '🟡',
  'ounce': '🪙 ',
  'bitcoin': '₿',
  };

  static Map<String, Color> currencyColors = {
  'usd': const Color.fromARGB(255, 69, 98, 202),
  'eur': const Color.fromARGB(255, 27, 77, 255),
  'gbp': const Color.fromARGB(255, 0, 137, 137),
  'chf': const Color.fromARGB(255, 255, 101, 140),
  'cad': const Color.fromARGB(255, 255, 17, 0),
  'aud': const Color.fromARGB(255, 72, 58, 202),
  'sek': const Color.fromARGB(255, 255, 247, 0),
  'nok': const Color.fromARGB(255, 202, 71, 62),
  'rub': const Color.fromARGB(255, 198, 6, 18),
  'thb': const Color.fromARGB(255, 180, 66, 215),
  'sgd': const Color.fromARGB(255, 255, 179, 198),
  'hkd': const Color.fromARGB(255, 244, 151, 142),
  'azn': const Color.fromARGB(255, 131, 197, 190),
  'amd': const Color.fromARGB(255, 253, 53, 1),
  'dkk': const Color.fromARGB(255, 180, 70, 62),
  'aed': const Color.fromARGB(255, 99, 99, 99),
  'jpy': const Color.fromARGB(255, 213, 26, 54),
  'try': const Color.fromARGB(255, 230, 41, 28),
  'cny': const Color.fromARGB(255, 246, 16, 0),
  'sar': const Color.fromARGB(255, 0, 183, 49),
  'inr': const Color.fromARGB(255, 226, 149, 120),
  'irr': const Color.fromARGB(255, 54, 54, 54),
  'myr': const Color.fromARGB(255, 84, 0, 149),
  'afn': const Color.fromARGB(255, 79, 104, 62),
  'kwd': const Color.fromARGB(255, 31, 138, 76),
  'iqd': const Color.fromARGB(255, 173, 55, 61),
  'bhd': const Color.fromARGB(255, 255, 0, 110),
  'omr': const Color.fromARGB(255, 255, 77, 109),
  'qar': const Color.fromARGB(255, 141, 0, 16),
  'emami1': const Color.fromARGB(255, 54, 54, 54),
  'azadi1g': const Color.fromARGB(255, 255, 205, 54),
  'azadi1': const Color.fromARGB(255, 255, 205, 54),
  'azadi1_2': const Color.fromARGB(255, 255, 205, 54),
  'azadi1_4': const Color.fromARGB(255, 255, 205, 54),
  'mithqal': const Color.fromARGB(255, 172, 146, 79),
  'gol18': const Color.fromARGB(255, 255, 205, 54),
  'ounce': const Color.fromARGB(255, 54, 54, 54),
  'bitcoin': const Color.fromARGB(255, 255, 145, 0),
  };
}