name: Build APKs

on:
  push:
    branches:
      - main

jobs:
  android-release-build:
    name: Build Android APKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APKs using Flutter Android Build Action
        uses: NiklasLehnfeld/flutter-android-build-action@v2
        id: android-build
        with:
          release: true
          build-type: both

      - name: Upload APKs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: |
            ${{ steps.android-build.outputs.apk-path }}
            ${{ steps.android-build.outputs.aab-path }}
