name: Web Global

on:
  workflow_dispatch:

jobs:
  build-and-deploy-web:
    name: Build and Deploy Web
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          cache: true

      - name: Check Flutter version
        run: flutter --version

      - name: Cache Pub Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Flutter clean
        run: flutter clean

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Build Web App
        run: flutter build web --release --base-href=/ --web-renderer=html
        continue-on-error: false

      - name: Check Web Output
        run: |
          if [ -d "build/web" ]; then
            echo "Web build successful"
            echo "Listing contents of build/web:"
            ls -la build/web
          else
            echo "Web build failed - directory not found"
            exit 1
          fi

      - name: Prepare website worktree
        run: |
          git config --global user.name "Riyales"
          git config --global user.email "info@ryls.ir"
          git fetch origin website || true
          rm -rf website-dir || true
          git worktree add --force -B website website-dir origin/website || git worktree add --force -b website website-dir

      - name: Commit web build to website branch
        run: |
          rsync -av --delete build/web/ website-dir/
          cd website-dir
          touch .nojekyll
          git add .
          git commit -m "Deploy web build $(date +'%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"
          git push origin website --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup worktree
        if: always()
        run: git worktree remove website-dir

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: riyales
          directory: build/web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          commit-dirty: true

  cleanup:
    name: Cleanup
    if: always()
    runs-on: ubuntu-latest
    permissions:
      actions: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO:    ${{ github.repository }}
      WF:      ${{ github.workflow }}
    steps:
      - name: Remove old workflow runs
        run: |
          runs=$(gh run list \
            --repo "$REPO" \
            --workflow "$WF" \
            --limit 100 \
            --json databaseId,status,createdAt \
            --jq '.[] | select(.status!="in_progress" and .status!="queued") | {id: .databaseId, date: .createdAt}' | \
            jq -s 'sort_by(.date) | reverse | .[].id')
          total=$(echo "$runs" | wc -l)
          if [ "$total" -le 9 ]; then exit 0; fi
          to_delete=$(echo "$runs" | tail -n +10)
          echo "$to_delete" | while read id; do
            echo "Deleting run ID: $id"
            gh run delete "$id" --repo "$REPO"
          done
        shell: bash
