name: Release iOS

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      upgrade_flutter:
        description: 'Upgrade Flutter to the latest stable version (true/false)'
        required: false
        default: 'false'

env:
  FLUTTER_VERSION: '3.32.6'
  DART_VERSION: '3.8.1'
  BUNDLE_ID: 'ir.ryls'

jobs:
  build:
    name: Build iOS IPA
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Dart SDK
        uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/dart-sdk
          key: ${{ runner.os }}-dart-${{ env.DART_VERSION }}
          restore-keys: |
            ${{ runner.os }}-dart-

      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: |
            ${{ runner.tool_cache }}/flutter
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}-${{ env.FLUTTER_VERSION }}
          restore-keys: |
            ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}-
            ${{ runner.os }}-flutter-

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Upgrade Flutter (optional)
        if: github.event.inputs.upgrade_flutter == 'true'
        run: flutter upgrade --force

      - name: Check Flutter and Dart versions
        run: |
          flutter --version
          dart --version

      - name: Cache Dart dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-dart-deps-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-dart-deps-

      - name: Install dependencies
        run: flutter pub get

      - name: Update iOS bundle identifier
        run: |
          echo "Setting iOS bundle ID to ${{ env.BUNDLE_ID }}"
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier ${{ env.BUNDLE_ID }}" ios/Runner/Info.plist
          sed -i '' 's/PRODUCT_BUNDLE_IDENTIFIER = .*;/PRODUCT_BUNDLE_IDENTIFIER = ${{ env.BUNDLE_ID }};/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Build iOS IPA (unsigned)
        run: |
          # Build iOS without code signing
          flutter build ios --release --no-codesign
          
          # Create IPA manually from the .app bundle
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../ipa/riyales-${{ env.APP_VERSION }}.ipa Payload/
          # Create zip of Runner.app
          zip -r ../ipa/riyales-app-${{ env.APP_VERSION }}.zip Runner.app
          # Create zip of IPA
          zip -r ../ipa/riyales-ipa-${{ env.APP_VERSION }}.zip ../ipa/riyales-${{ env.APP_VERSION }}.ipa
          cd ../../..
          
          # Verify outputs
          ls -la build/ios/ipa/

      - name: Extract version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
          echo "Extracted version: $VERSION"
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: riyales-ipa
          path: |
            build/ios/ipa/riyales-${{ env.APP_VERSION }}.ipa
            build/ios/ipa/riyales-app-${{ env.APP_VERSION }}.zip
            build/ios/ipa/riyales-ipa-${{ env.APP_VERSION }}.zip

  release:
    name: Publish Release Assets
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Extract version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
          echo "Extracted version: $VERSION"
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - uses: actions/download-artifact@v4
        name: Download IPA artifacts
        with:
          name: riyales-ipa
          path: artifacts/ipa

      - name: Attach IPA and zips to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ env.APP_VERSION }}
          name: Release v${{ env.APP_VERSION }}
          files: |
            artifacts/ipa/riyales-${{ env.APP_VERSION }}.ipa
            artifacts/ipa/riyales-app-${{ env.APP_VERSION }}.zip
            artifacts/ipa/riyales-ipa-${{ env.APP_VERSION }}.zip

  cleanup:
    name: Cleanup Old Workflow Runs
    if: always()
    runs-on: ubuntu-latest
    permissions:
      actions: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: ${{ github.repository }}
      WF: ${{ github.workflow }}
    steps:
      - name: Remove old workflow runs
        run: |
          runs=$(gh run list \
            --repo "$REPO" \
            --workflow "$WF" \
            --limit 100 \
            --json databaseId,status,createdAt \
            --jq '.[] | select(.status!="in_progress" and .status!="queued") | {id: .databaseId, date: .createdAt}' | \
            jq -s 'sort_by(.date) | reverse | .[].id')
          total=$(echo "$runs" | wc -l)
          if [ "$total" -le 9 ]; then exit 0; fi
          # delete all older than the 9 newest
          to_delete=$(echo "$runs" | tail -n +10)
          echo "$to_delete" | while read id; do
            echo "Deleting run ID: $id"
            gh run delete "$id" --repo "$REPO"
          done
        shell: bash
