name: Android APK CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SKIP_JDK_VERSION_CHECK: true

jobs:
  build:
    name: Build Universal APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          cache: true

      - name: Cache Pub Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Set up Android SDK & accept licenses
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools: '33.0.2'
          cmake: '3.22.1'
          ndk: '23.1.7779620'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (Universal)
        run: flutter build apk --release

      - name: Zip APK artifact
        working-directory: build/app/outputs/flutter-apk
        run: zip riyales-universal.zip app-release.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: riyales-apk
          path: build/app/outputs/flutter-apk/riyales-universal.zip

      - name: Build Web App
        run: flutter build web --release

      - name: Zip Web artifact
        working-directory: build/web
        run: zip -r riyales-web.zip .

      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: riyales-web
          path: build/web/riyales-web.zip

      - name: Build Linux App Bundle
        run: flutter build linux --release

      - name: Download linuxdeploy
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage -O linuxdeploy
          chmod +x linuxdeploy

      - name: Prepare AppDir
        run: |
          mkdir -p AppDir/usr/{bin,share/applications,share/icons/hicolor/256x256/apps}
          cp build/linux/x64/release/bundle/riyales AppDir/usr/bin/
          cp assets/icons/application/android/mipmap-xxxhdpi/riyales.png AppDir/usr/share/icons/hicolor/256x256/apps/riyales.png
          cat > AppDir/usr/share/applications/riyales.desktop << 'EOF'
          [Desktop Entry]
          Type=Application
          Name=Riyales
          Exec=riyales
          Icon=riyales
          Terminal=false
          EOF

      - name: Generate AppImage
        run: ./linuxdeploy --appdir AppDir --output appimage

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: riyales-appimage
          path: '*.AppImage'

  deploy-web:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: build/web

  release:
    name: Publish Release Assets
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: riyales-apk
          path: artifacts/apk
      - uses: actions/download-artifact@v4
        with:
          name: riyales-web
          path: artifacts/web
      - uses: actions/download-artifact@v4
        with:
          name: riyales-appimage
          path: artifacts/appimage
      - id: create_release
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/apk/riyales-universal.zip
          asset_name: riyales-universal.zip
          asset_content_type: application/zip
      - name: Upload Web to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/web/riyales-web.zip
          asset_name: riyales-web.zip
          asset_content_type: application/zip
      - name: Upload AppImage to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/appimage/*.AppImage
          asset_name: riyales.AppImage
          asset_content_type: application/octet-stream
